### ISSUE TITLE
plz help was been stuck for many days

### ISSUE THREAD

**Issue by xalteropsx** [Tohrusky/realesrgan-ncnn-py#10]
@Tohrusky i try to compile https://github.com/FeiGeChuanShu/CodeFormer-ncnn

when i get the codeformer.exe i do run it take only cpu usage not gpu around 50-70% also it doesn't give the result either. Can u provide yours visual studio file would be a great help 
if dont have ur vs project can share mine if not do u have  any suggestion why it dont work 

kinda have been stuck for like 10-12days on it

**Comment by Tohrusky** [comment]
I don't use vs, I use Clion
And I don't write C++ bro, If I remember correctly all FeiGeChuanShu's ncnn projects just got CPU support

**Comment by xalteropsx** [comment]
agreed i didnt notice it was cpu base my ncnn was currpt i rework and it start giving result but yah pretty slow with cpu


thnx for ur quick reply >.</ may be i got little closer now can get result will see i think cpu i faster in restore face model just the upscale was wrong so i change one line vulakan true for ersgan and it now work good

**Comment by Tohrusky** [comment]
> agreed i didnt notice it was cpu base my ncnn was currpt i rework and it start giving result but yah pretty slow with cpu
> 
> 
> 
> 
> 
> thnx for ur quick reply >.</ may be i got little closer now can get result will see i think cpu i faster in restore face model just the upscale was wrong so i change one line vulakan true for ersgan and it now work good 

yes, the ops which esrgan used are all fully supported in ncnn -- cuz it's just a simple network lol

Maybe you need to write custom op to get full gpu support, and before that check ncnn's latest ops first I think

**Comment by xalteropsx** [comment]
someone build this library recently not sure if support or not  // but feel like most of previous repo of FeiGeChuanShu code
https://github.com/onuralpszr/GFPGAN-ncnn-vulkan/tree/main

but although i get some error on jpg and png not with webp like i created an issue
