### ISSUE TITLE
Verbosity Flag option

### ISSUE THREAD

**Issue by NevermindNilas** [Tohrusky/realesrgan-ncnn-py#7]
Hi, in the realesrgan.cpp file there's a print statement at lines  548 and 869

`fprintf(stderr, "%.2f%%\n", (float) (yi * xtiles + xi) / (ytiles * xtiles) * 100);`

![image (5)](https://github.com/Final2x/realesrgan-ncnn-py/assets/128264457/54cc2a89-3d6f-4cf3-b9ff-74ed8e5c9ddb)

These lines seem to quickly fill up the terminal for no real benefit.

Would it be possible to add a flag to turn them off?

**Comment by xalteropsx** [comment]
@NevermindNilas did u find the answer I also want to hide them

**Comment by NevermindNilas** [comment]
I just ended up forking the repository and removing the prints myself not too long after making the issue.

**Comment by xalteropsx** [comment]
me took me like 6hr to figure but thnx for ur respond >.< annoying bugs first time c++

**Comment by Tohrusky** [comment]
I've been a little busy lately, so I'm not going to take care of this project for a while...

**Comment by xalteropsx** [comment]
its all good we both done it >.</ between thnx tohrusky its all ur hard work which help us to save time may god bless u

**Comment by voidpenguin-28** [comment]
For those in the future looking for a simple solution for this without needing to modify any existing code from this repo, below is an approach to do so.

Basically, any stderr output within the specified scope (while the image is being processed) will be thrown away.
Extra precautions would need to be taken to make this thread-safe, keep this in mind.

```python

import os
import sys
import numpy as np
import cv2
from realesrgan_ncnn_py import Realesrgan
from contextlib import contextmanager


realesrgan = Realesrgan(gpuid = 0)

@contextmanager
def suppress_stderr():
    # Open the null device for writing.
    with open("nul", "w") as devnull:
        # Save the original file descriptor for stderr (2).
        old_stderr = os.dup(2)
        try:
            os.dup2(devnull.fileno(), 2)
            yield
        finally:
            os.dup2(old_stderr, 2)
            os.close(old_stderr)

def upscale(img_path, output_dir):
    img_name = os.path.basename(img_path)
    img_ext = '.' + img_name.split('.')[-1]
    output_path = os.path.join(output_dir, img_name)
    
    image = cv2.imdecode(np.fromfile(img_path, dtype=np.uint8), cv2.IMREAD_COLOR)
    
    with suppress_stderr():
        image = realesrgan.process_cv2(image)
    
    cv2.imencode(img_ext, image)[1].tofile(output_path)
    return output_path


input_file = 'in/image1.jpg'
output_dir = 'out/'

output_file = upscale(input_file, output_dir)

```
-----
The key statement here being:
```python
with suppress_stderr():
        image = realesrgan.process_cv2(image)
```
